skeleton.test:
  hostname: 159.65.19.94
  user: impressdev
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - app
    - db
  deploy_path: ~/files
